### ISSUE TITLE
关于hive中tinyint类型的支持

### ISSUE THREAD

**Issue by balajinima** [stuxuhai/HData#11]
从mysql到hive，如果hive字段类型是tinyint会报错，
------------------------------------------------------
hive中表结构
CREATE TABLE `tt2`(
      `id` tinyint, 
       `nm` string);
--------------------------------------------------------
错误：

2016-08-12 17:46:20.715 [pool-3-thread-1] ERROR com.github.stuxuhai.hdata.core.RecordEventExceptionHandler - java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Byte
	at org.apache.hadoop.hive.serde2.objectinspector.primitive.JavaByteObjectInspector.get(JavaByteObjectInspector.java:40)
	at org.apache.hadoop.hive.serde2.lazy.LazyUtils.writePrimitiveUTF8(LazyUtils.java:194)
	at org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe.serialize(LazySimpleSerDe.java:307)
	at org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe.serializeField(LazySimpleSerDe.java:262)
	at org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe.doSerialize(LazySimpleSerDe.java:246)
	at org.apache.hadoop.hive.serde2.AbstractEncodingAwareSerDe.serialize(AbstractEncodingAwareSerDe.java:50)
	at org.apache.hive.hcatalog.mapreduce.FileRecordWriterContainer.write(FileRecordWriterContainer.java:122)
	at org.apache.hive.hcatalog.mapreduce.FileRecordWriterContainer.write(FileRecordWriterContainer.java:54)
	at com.github.stuxuhai.hdata.plugin.writer.hive.HiveWriter.execute(HiveWriter.java:141)
	at com.github.stuxuhai.hdata.core.RecordWorkHandler.onEvent(RecordWorkHandler.java:36)
	at com.github.stuxuhai.hdata.core.RecordWorkHandler.onEvent(RecordWorkHandler.java:9)
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:139)
	at java.lang.Thread.run(Thread.java:745)

**Comment by stuxuhai** [comment]
mysql和hive的字段类型没有对应上
