### ISSUE TITLE
It can't write csv

### ISSUE THREAD

**Issue by vividcao** [stuxuhai/HData#17]
2016-09-01 22:11:36.463 [main] INFO  com.github.stuxuhai.hdata.core.HData - Reader parallelism: 3, Writer parallelism: 1
2016-09-01 22:11:36.472 [main] ERROR com.github.stuxuhai.hdata.CliDriver - null
	at com.github.stuxuhai.hdata.config.DefaultJobConfig.newWriter(DefaultJobConfig.java:82)
	at com.github.stuxuhai.hdata.core.HData.start(HData.java:111)
	at com.github.stuxuhai.hdata.CliDriver.main(CliDriver.java:148)
Caused by: java.lang.ClassNotFoundException: com.github.stuxuhai.hdata.plugin.reader.csv.CSVWriter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.github.stuxuhai.hdata.core.PluginClassLoader.loadClass(PluginClassLoader.java:18)
	at com.github.stuxuhai.hdata.util.PluginUtils.loadClass(PluginUtils.java:46)
	at com.github.stuxuhai.hdata.config.DefaultJobConfig.newWriter(DefaultJobConfig.java:80)
	... 2 more
总提示这个

**Comment by vividcao** [comment]
我输出--writer console都是可以正常输出的。
但是输出 --write csv -Wpath="path/to/test.csv" 就总是报这个错。

**Comment by vividcao** [comment]
The plugins.xml is wrong for csv write.
