### ISSUE TITLE
not support Hadoop HA

### ISSUE THREAD

**Issue by 144Lucky** [stuxuhai/HData#18]
when assign hdfs.conf.path 
        <property>
                <name>dfs.nameservices</name>
                <value>cluster</value>
        </property>

Caused by: org.apache.hive.hcatalog.common.HCatException : 2001 : Error setting output information. Cause : java.lang.IllegalArgumentException: java.net.UnknownHostException: cluster
	at org.apache.hive.hcatalog.mapreduce.HCatOutputFormat.setOutput(HCatOutputFormat.java:220)
	at org.apache.hive.hcatalog.mapreduce.HCatOutputFormat.setOutput(HCatOutputFormat.java:70)
	at com.github.stuxuhai.hdata.plugin.writer.hive.HiveWriter.prepare(HiveWriter.java:101)
	... 4 more

**Comment by 144Lucky** [comment]
the last Kylin solve the problem,

**Comment by stuxuhai** [comment]
```xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>

<configuration>
    <property>
        <name>fs.defaultFS</name>
        <value></value>
    </property>
    <property>
        <name>ha.zookeeper.quorum</name>
        <value></value>
    </property>
    <property>
        <name>dfs.nameservices</name>
        <value></value>
    </property>
    <property>
        <name>dfs.ha.namenodes.XXX</name>
        <value></value>
    </property>
    <property>
        <name>dfs.namenode.rpc-address.XXX.nn1</name>
        <value></value>
    </property>
    <property>
        <name>dfs.namenode.rpc-address.XXX.nn2</name>
        <value></value>
    </property>
    <property>
        <name>dfs.namenode.http-address.XXX.nn1</name>
        <value></value>
    </property>
    <property>
        <name>dfs.namenode.http-address.XXX.nn2</name>
        <value></value>
    </property>
    <property>
        <name>dfs.ha.automatic-failover.enabled</name>
        <value>true</value>
    </property>
    <property>
        <name>dfs.client.failover.proxy.provider.mgjcluster</name>
        <value>org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider</value>
    </property>
</configuration>

````

**Comment by 144Lucky** [comment]
thanks very much ,have solved
