### ISSUE TITLE
writing data to Hbase ,how config rowkey

### ISSUE THREAD

**Issue by 144Lucky** [stuxuhai/HData#19]
I want to reader data from Mongo to Hbase ,how i config the rowkey.

**Comment by stuxuhai** [comment]
map Mongo fields in order to hbase writer, and set writer configuration:
-Wcolumns=:rowkey,cf1:c1,cf1:c2,cf1:c3

:rowkey => rowkey
cf1:c1 => column family: cf1    column: c1

**Comment by 144Lucky** [comment]
thanks reponse quickly, the rowkey need to do something,such as compose two colums,convert datatype timestamp to int ,add a random number.


thus ,as the code resource ,i change the columns as follow:
`<columns>cf1:c1, :rowkey,cf1:c2,cf1:c3</columns>`

errors occur:
2016-09-09 16:40:09.220 [pool-3-thread-1] ERROR 

com.github.stuxuhai.hdata.core.RecordEventExceptionHandler - null
	at com.github.stuxuhai.hdata.plugin.writer.hbase.HBaseWriter.prepare(HBaseWriter.java:59)
	at com.github.stuxuhai.hdata.core.RecordWorkHandler.onEvent(RecordWorkHandler.java:29)
	at com.github.stuxuhai.hdata.core.RecordWorkHandler.onEvent(RecordWorkHandler.java:9)
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:139)
	at java.lang.Thread.run(Thread.java:745)

**Comment by stuxuhai** [comment]
now hdata doesn't support compose two columns or add a random number as rowkey.

remove the space character:
`<columns>cf1:c1,:rowkey,cf1:c2,cf1:c3</columns>`

**Comment by 144Lucky** [comment]
removed the space character, still the same problem

**Comment by stuxuhai** [comment]
What't the exception?

**Comment by 144Lucky** [comment]
com.github.stuxuhai.hdata.core.RecordEventExceptionHandler - null
at com.github.stuxuhai.hdata.plugin.writer.hbase.HBaseWriter.prepare(HBaseWriter.java:59)
at com.github.stuxuhai.hdata.core.RecordWorkHandler.onEvent(RecordWorkHandler.java:29)
at com.github.stuxuhai.hdata.core.RecordWorkHandler.onEvent(RecordWorkHandler.java:9)
at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:139)
at java.lang.Thread.run(Thread.java:745)
