### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by LanstonWu** [stuxuhai/HData#37]
Java version:1.8.0_111
安装后配置从oracle导出csv文件,运行时报如下的错误
`
./hdata -f job.xml 
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.commons.cli.Option.builder(Ljava/lang/String;)Lorg/apache/commons/cli/Option$Builder;
	at com.github.stuxuhai.hdata.CliDriver.createOptions(CliDriver.java:46)
	at com.github.stuxuhai.hdata.CliDriver.main(CliDriver.java:101)
`
大家好,我对java不是很熟悉,请教下是那里配置错误还是缺少什么包吗?

**Comment by zqq90** [comment]
提供一下目录结构吧， 看一下都有哪些 jar
例如
```sh
$ tree
.
├── bin
│   └── hdata
├── lib
│   ├── asm-3.3.1.jar
。。。。
│   └── slf4j-api-1.7.12.jar
└── plugins
    ├── console
    │   ├── commons-logging-1.2.jar
```

**Comment by LanstonWu** [comment]
谢谢帮助,检查了jar包确实有多个版本存在.
`
$ ls lib/commons-cli*
lib/commons-cli-1.0.jar  lib/commons-cli-1.2.jar  lib/commons-cli-1.2-sources.jar  lib/commons-cli-1.3.1.jar
`
我仅保留1.3.1版本后正常.
**下面是使用过程中遇到的一些jar包问题**;
lib/jcl-over-slf4j-1.5.6.jar 这个包不能导入,导入报错;
`
Exception in thread "main" java.lang.NoSuchMethodError: org.slf4j.spi.LocationAwareLogger.log(Lorg/slf4j/Marker;Ljava/lang/String;ILjava/lang/String;Ljava/lang/Throwable;)V
	at org.apache.commons.logging.impl.SLF4JLocationAwareLog.debug(SLF4JLocationAwareLog.java:120)
	at org.apache.commons.configuration.ConfigurationUtils.locate(ConfigurationUtils.java:449)
	at org.apache.commons.configuration.AbstractFileConfiguration.load(AbstractFileConfiguration.java:255)
	at org.apache.commons.configuration.AbstractFileConfiguration.load(AbstractFileConfiguration.java:238)
	at org.apache.commons.configuration.AbstractHierarchicalFileConfiguration.load(AbstractHierarchicalFileConfiguration.java:184)
	at org.apache.commons.configuration.AbstractHierarchicalFileConfiguration.<init>(AbstractHierarchicalFileConfiguration.java:95)
	at org.apache.commons.configuration.XMLConfiguration.<init>(XMLConfiguration.java:261)
	at com.github.stuxuhai.hdata.config.DefaultJobConfig.createFromXML(DefaultJobConfig.java:84)
	at com.github.stuxuhai.hdata.CliDriver.main(CliDriver.java:121)
`
lib/commons-lang-2.1.jar 这个版本的包不能导入,导入报错;
`
$ bin/hdata -f bin/job.xml
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.commons.lang.StringUtils.join(Ljava/util/Collection;Ljava/lang/String;)Ljava/lang/String;
	at com.github.stuxuhai.hdata.config.DefaultJobConfig.createFromXML(DefaultJobConfig.java:94)
	at com.github.stuxuhai.hdata.CliDriver.main(CliDriver.java:121)
`
