### ISSUE TITLE
希望能提供链接oracle的demo写法和java包

### ISSUE THREAD

**Issue by TimeIsGoOn** [stuxuhai/HData#4]
希望能给个连接到oracle的demo写法,提供Oracle的jdbc驱动jar包,或者提供个地址也行
我在oracle的官网找到好多,不知道哪个是(我不懂java开发)
[oracle的官网](http://www.oracle.com/technetwork/database/enterprise-edition/jdbc-112010-090769.html)

十分感谢

**Comment by TimeIsGoOn** [comment]
我下了一个ojdbc6.jar文件,放到了hdata/plugins/jdbc目录下
配置文件如下

```
<?xml version="1.0" encoding="UTF-8"?>
<job id="job_example">
    <reader name="jdbc">
        <url>jdbc:oracle://192.168.14.99:1521/eai</url>
        <driver>com.oracle.jdbc.Driver</driver>
        <table>V_TH_CJ_YX_SBZK_HB</table>
        <username>eai_view</username>
        <password>eai_view</password>
        <parallelism>3</parallelism>
    </reader>

    <writer name="mongodb">
        <uri>mongodb://localhost/test.oracle</uri>
    </writer>
</job>

```

运行报错
```
➜  hdata ./bin/hdata -f conf/oracle.xml
2016-07-13 14:54:36.817 [main] INFO  com.github.stuxuhai.hdata.core.HData - Reader: jdbc, Writer: mongodb
2016-07-13 14:54:36.864 [main] ERROR com.github.stuxuhai.hdata.CliDriver - null
	at com.github.stuxuhai.hdata.config.DefaultJobConfig.newReader(DefaultJobConfig.java:72)
	at com.github.stuxuhai.hdata.config.DefaultJobConfig.newSplitter(DefaultJobConfig.java:78)
	at com.github.stuxuhai.hdata.core.HData.start(HData.java:73)
	at com.github.stuxuhai.hdata.CliDriver.main(CliDriver.java:155)
Caused by: null
	at com.github.stuxuhai.hdata.util.PluginUtils.listFileByPluginName(PluginUtils.java:37)
	at com.github.stuxuhai.hdata.util.PluginUtils.loadClass(PluginUtils.java:49)
	at com.github.stuxuhai.hdata.config.DefaultJobConfig.newReader(DefaultJobConfig.java:70)
	... 3 more

```

**Comment by TimeIsGoOn** [comment]
大神求助

**Comment by stuxuhai** [comment]
你安装在什么路径下

**Comment by TimeIsGoOn** [comment]
```
➜  /tmp cd hdata 
➜  hdata ls
bin  conf  lib  pei  plugins
➜  hdata ./bin/hdata -f conf/oracle.xml
2016-07-13 16:34:51.789 [main] INFO  com.github.stuxuhai.hdata.core.HData - Reader: jdbc, Writer: mongodb
2016-07-13 16:34:51.864 [main] INFO  com.github.stuxuhai.hdata.core.HData - Executing splitter for reader.
2016-07-13 16:34:51.876 [pool-2-thread-1] INFO  com.github.stuxuhai.hdata.plugin.reader.jdbc.JDBCSplitter - Attempt to query digital primary key for table: V_TH_CJ_YX_SBZK_HB
2016-07-13 16:34:51.889 [main] ERROR com.github.stuxuhai.hdata.core.HData - 
java.util.concurrent.ExecutionException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.7.0_101]
	at java.util.concurrent.FutureTask.get(FutureTask.java:188) ~[?:1.7.0_101]
	at com.github.stuxuhai.hdata.core.HData.start(HData.java:89) [hdata-core-0.2.8.jar:?]
	at com.github.stuxuhai.hdata.CliDriver.main(CliDriver.java:155) [hdata-core-0.2.8.jar:?]
Caused by: com.github.stuxuhai.hdata.exception.HDataException: java.lang.ClassNotFoundException: com.oracle.jdbc.Driver
	at com.github.stuxuhai.hdata.plugin.reader.jdbc.JDBCSplitter.split(JDBCSplitter.java:181) ~[?:?]
	at com.github.stuxuhai.hdata.core.HData$1.call(HData.java:82) ~[hdata-core-0.2.8.jar:?]
	at com.github.stuxuhai.hdata.core.HData$1.call(HData.java:78) ~[hdata-core-0.2.8.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) ~[?:1.7.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[?:1.7.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[?:1.7.0_101]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.7.0_101]
Caused by: java.lang.ClassNotFoundException: com.oracle.jdbc.Driver
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[?:1.7.0_101]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_101]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_101]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_101]
	at com.github.stuxuhai.hdata.core.PluginClassLoader.loadClass(PluginClassLoader.java:26) ~[hdata-core-0.2.8.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.7.0_101]
	at java.lang.Class.forName(Class.java:195) ~[?:1.7.0_101]
	at com.github.stuxuhai.hdata.util.JdbcUtils.getConnection(JdbcUtils.java:208) ~[hdata-core-0.2.8.jar:?]
	at com.github.stuxuhai.hdata.plugin.reader.jdbc.JDBCSplitter.split(JDBCSplitter.java:171) ~[?:?]
	at com.github.stuxuhai.hdata.core.HData$1.call(HData.java:82) ~[hdata-core-0.2.8.jar:?]
	at com.github.stuxuhai.hdata.core.HData$1.call(HData.java:78) ~[hdata-core-0.2.8.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) ~[?:1.7.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[?:1.7.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[?:1.7.0_101]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.7.0_101]
➜  hdata 
➜  hdata pwd      
/tmp/hdata
➜  hdata 

```

**Comment by TimeIsGoOn** [comment]
jdbc文件放在了这里

```

➜  hdata ls      
bin  conf  lib  pei  plugins
➜  hdata cd plugins 
➜  plugins ls
console  csv  excel  ftp  hbase  hdfs  hive  http  jdbc  kafka  mongodb
➜  plugins cd jdbc   
➜  jdbc ls
asm-3.3.1.jar                   commons-digester3-3.2.jar       hdata-api-0.2.8.jar    log4j-jcl-2.5.jar
cglib-2.2.2.jar                 commons-lang-2.6.jar            hdata-core-0.2.8.jar   log4j-jul-2.5.jar
commons-beanutils-1.9.2.jar     commons-lang3-3.4.jar           hdata-jdbc-0.2.8.jar   log4j-slf4j-impl-2.5.jar
commons-cli-1.3.1.jar           commons-logging-1.2.jar         java-sizeof-0.0.5.jar  mysql-connector-java-5.1.38.jar
commons-collections-3.2.2.jar   disruptor-3.3.4.jar             log4j-1.2-api-2.5.jar  ojdbc6.jar
commons-configuration-1.10.jar  eigenbase-properties-1.1.5.jar  log4j-api-2.5.jar      simplefan.jar
commons-dbutils-1.6.jar         guava-19.0.jar                  log4j-core-2.5.jar     slf4j-api-1.7.12.jar
➜  jdbc 
```

**Comment by stuxuhai** [comment]
Caused by: java.lang.ClassNotFoundException: com.oracle.jdbc.Driver

驱动类不对吧，应该是 oracle.jdbc.driver.OracleDriver

**Comment by TimeIsGoOn** [comment]
最新的config

```
<?xml version="1.0" encoding="UTF-8"?>

<job id="job_example">
    <reader name="jdbc">
        <url>jdbc:oracle://192.168.14.99:1521/eai</url>
        <driver>oracle.jdbc.driver.OracleDriver</driver>
        <table>V_TH_CJ_YX_SBZK_HB</table>
        <username>eai_view</username>
        <password>eai_view</password>
        <parallelism>3</parallelism>
    </reader>

    <writer name="mongodb">
        <uri>mongodb://localhost/test.oracle</uri>
    </writer>
</job>

```

报错

```

➜  hdata ./bin/hdata -f conf/oracle.xml
2016-07-13 17:07:27.654 [main] INFO  com.github.stuxuhai.hdata.core.HData - Reader: jdbc, Writer: mongodb
2016-07-13 17:07:27.718 [main] INFO  com.github.stuxuhai.hdata.core.HData - Executing splitter for reader.
2016-07-13 17:07:27.730 [pool-2-thread-1] INFO  com.github.stuxuhai.hdata.plugin.reader.jdbc.JDBCSplitter - Attempt to query digital primary key for table: V_TH_CJ_YX_SBZK_HB
2016-07-13 17:07:27.799 [main] ERROR com.github.stuxuhai.hdata.core.HData - 
java.util.concurrent.ExecutionException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.7.0_101]
	at java.util.concurrent.FutureTask.get(FutureTask.java:188) ~[?:1.7.0_101]
	at com.github.stuxuhai.hdata.core.HData.start(HData.java:89) [hdata-core-0.2.8.jar:?]
	at com.github.stuxuhai.hdata.CliDriver.main(CliDriver.java:155) [hdata-core-0.2.8.jar:?]
Caused by: com.github.stuxuhai.hdata.exception.HDataException: java.sql.SQLException: 指定了无效的 Oracle URL
	at com.github.stuxuhai.hdata.plugin.reader.jdbc.JDBCSplitter.split(JDBCSplitter.java:181) ~[?:?]
	at com.github.stuxuhai.hdata.core.HData$1.call(HData.java:82) ~[hdata-core-0.2.8.jar:?]
	at com.github.stuxuhai.hdata.core.HData$1.call(HData.java:78) ~[hdata-core-0.2.8.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) ~[?:1.7.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[?:1.7.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[?:1.7.0_101]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.7.0_101]
Caused by: java.sql.SQLException: 指定了无效的 Oracle URL
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:441) ~[?:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:571) ~[?:1.7.0_101]
	at java.sql.DriverManager.getConnection(DriverManager.java:215) ~[?:1.7.0_101]
	at com.github.stuxuhai.hdata.util.JdbcUtils.getConnection(JdbcUtils.java:209) ~[hdata-core-0.2.8.jar:?]
	at com.github.stuxuhai.hdata.plugin.reader.jdbc.JDBCSplitter.split(JDBCSplitter.java:171) ~[?:?]
	at com.github.stuxuhai.hdata.core.HData$1.call(HData.java:82) ~[hdata-core-0.2.8.jar:?]
	at com.github.stuxuhai.hdata.core.HData$1.call(HData.java:78) ~[hdata-core-0.2.8.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) ~[?:1.7.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[?:1.7.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[?:1.7.0_101]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.7.0_101]
➜  hdata 

```

我测试过了,oracle数据库是可以用的.

**Comment by TimeIsGoOn** [comment]
我怀疑还是jdbc链接oracle的包不对

**Comment by stuxuhai** [comment]
把jdbc:oracle://192.168.14.99:1521/eai改成jdbc:oracle:thin:@192.168.14.99:1521:eai

**Comment by TimeIsGoOn** [comment]
大神求助:

```
<?xml version="1.0" encoding="UTF-8"?>

<job id="job_example">
    <reader name="jdbc">
        <url>jdbc:oracle:thin:@192.168.14.99:1521:eai</url>
        <driver>oracle.jdbc.driver.OracleDriver</driver>
        <table>V_TH_CJ_YX_SBZK_HB</table>
        <username>eai_view</username>
        <password>eai_view</password>
        <parallelism>3</parallelism>
    </reader>

    <writer name="mongodb">
        <uri>mongodb://localhost/test.oracle</uri>
    </writer>
</job>

```

报错

```
➜  hdata ./bin/hdata -f conf/oracle.xml
2016-07-13 17:18:35.234 [main] INFO  com.github.stuxuhai.hdata.core.HData - Reader: jdbc, Writer: mongodb
2016-07-13 17:18:35.288 [main] INFO  com.github.stuxuhai.hdata.core.HData - Executing splitter for reader.
2016-07-13 17:18:35.303 [main] INFO  com.github.stuxuhai.hdata.core.HData - Reader parallelism: 1, Writer parallelism: 1
2016-07-13 17:18:35.331 [main] INFO  com.github.stuxuhai.hdata.core.HData - Transfer data from reader to writer...
2016-07-13 17:18:35.333 [main] INFO  com.github.stuxuhai.hdata.core.DefaultRecordCollector - The flow limit is 0 bytes/s.
2016-07-13 17:18:38.334 [main] INFO  com.github.stuxuhai.hdata.core.HData - Read: 0	Write: 0
2016-07-13 17:18:38.336 [main] INFO  com.github.stuxuhai.hdata.core.HData - Read Finished(total: 0), Write Finished(total: 0)
2016-07-13 17:18:38.347 [main] ERROR com.github.stuxuhai.hdata.core.HData - java.util.concurrent.ExecutionException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at com.github.stuxuhai.hdata.core.HData.start(HData.java:189)
	at com.github.stuxuhai.hdata.CliDriver.main(CliDriver.java:155)
Caused by: null
	at com.github.stuxuhai.hdata.plugin.reader.jdbc.JDBCReader.execute(JDBCReader.java:107)
	at com.github.stuxuhai.hdata.core.ReaderWorker.call(ReaderWorker.java:34)
	at com.github.stuxuhai.hdata.core.ReaderWorker.call(ReaderWorker.java:16)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: 调用中的无效参数: setFetchSize
	at oracle.jdbc.driver.OracleStatement.setPrefetchInternal(OracleStatement.java:2854)
	at oracle.jdbc.driver.OracleStatement.setFetchSize(OracleStatement.java:4122)
	at oracle.jdbc.driver.OracleStatementWrapper.setFetchSize(OracleStatementWrapper.java:232)
	at com.github.stuxuhai.hdata.plugin.reader.jdbc.JDBCReader.execute(JDBCReader.java:85)
	... 8 more

2016-07-13 17:18:38.352 [main] INFO  com.github.stuxuhai.hdata.core.HData - Read spent time: 3.00s, Write spent time: 3.01s
2016-07-13 17:18:38.353 [main] INFO  com.github.stuxuhai.hdata.core.HData - Read records: 0.00/s, Write records: 0.00/s
```

**Comment by stuxuhai** [comment]
重新pull代码编译下，发现Oracle的setFetchSize不支持Integer.MIN_VALUE

**Comment by TimeIsGoOn** [comment]
不行,报错说字符错误
```
➜  hdata ./bin/hdata -f conf/oracle.xml        
2016-07-13 18:19:18.865 [main] INFO  com.github.stuxuhai.hdata.core.HData - Reader: jdbc, Writer: mongodb
2016-07-13 18:19:18.921 [main] INFO  com.github.stuxuhai.hdata.core.HData - Executing splitter for reader.
2016-07-13 18:19:18.940 [pool-2-thread-1] INFO  com.github.stuxuhai.hdata.plugin.reader.jdbc.JDBCSplitter - Attempt to query digital primary key for table: V_TH_CJ_YX_SBZK_HB
2016-07-13 18:19:20.282 [pool-2-thread-1] INFO  com.github.stuxuhai.hdata.plugin.reader.jdbc.JDBCSplitter - Table V_TH_CJ_YX_SBZK_HB can not find digital primary key.
2016-07-13 18:19:20.356 [pool-2-thread-1] WARN  com.github.stuxuhai.hdata.plugin.reader.jdbc.JDBCSplitter - Reader parallelism is set to 3, but the "split-by" config is not given, so reader parallelism is set to default value: 1.
2016-07-13 18:19:20.366 [main] INFO  com.github.stuxuhai.hdata.core.HData - Reader parallelism: 1, Writer parallelism: 1
2016-07-13 18:19:20.438 [main] INFO  com.github.stuxuhai.hdata.core.HData - Transfer data from reader to writer...
2016-07-13 18:19:20.445 [main] INFO  com.github.stuxuhai.hdata.core.DefaultRecordCollector - The flow limit is 0 bytes/s.
2016-07-13 18:19:23.446 [main] INFO  com.github.stuxuhai.hdata.core.HData - Read: 0	Write: 0
2016-07-13 18:19:23.448 [main] INFO  com.github.stuxuhai.hdata.core.HData - Read Finished(total: 0), Write Finished(total: 0)
2016-07-13 18:19:23.456 [main] ERROR com.github.stuxuhai.hdata.core.HData - java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.sql.SQLSyntaxErrorException: ORA-00911: 无效字符

	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at com.github.stuxuhai.hdata.core.HData.start(HData.java:179)
	at com.github.stuxuhai.hdata.CliDriver.main(CliDriver.java:148)
Caused by: java.lang.RuntimeException: java.sql.SQLSyntaxErrorException: ORA-00911: 无效字符

	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at com.github.stuxuhai.hdata.plugin.reader.jdbc.JDBCReader.executeSingle(JDBCReader.java:154)
	at com.github.stuxuhai.hdata.plugin.reader.jdbc.JDBCReader.execute(JDBCReader.java:94)
	at com.github.stuxuhai.hdata.core.ReaderWorker.call(ReaderWorker.java:27)
	at com.github.stuxuhai.hdata.core.ReaderWorker.call(ReaderWorker.java:9)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLSyntaxErrorException: ORA-00911: 无效字符

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:440)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:837)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:445)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:191)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:523)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:193)
	at oracle.jdbc.driver.T4CStatement.executeForDescribe(T4CStatement.java:852)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1153)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1275)
	at oracle.jdbc.driver.OracleStatement.executeQuery(OracleStatement.java:1477)
	at oracle.jdbc.driver.OracleStatementWrapper.executeQuery(OracleStatementWrapper.java:392)
	at com.github.stuxuhai.hdata.plugin.reader.jdbc.JDBCReader.executeSingle(JDBCReader.java:112)
	... 9 more

2016-07-13 18:19:23.462 [main] INFO  com.github.stuxuhai.hdata.core.HData - Read spent time: 3.00s, Write spent time: 3.01s
2016-07-13 18:19:23.463 [main] INFO  com.github.stuxuhai.hdata.core.HData - Read records: 0.00/s, Write records: 0.00/s

```

**Comment by TimeIsGoOn** [comment]
大神你看看这个,[ORA-00911: 无效字符](http://blog.csdn.net/zjx2388/article/details/2164755)
是不是sql的拼装错了

**Comment by stuxuhai** [comment]
拼的SQL是 SELECT * FROM `V_TH_CJ_YX_SBZK_HB`

**Comment by TimeIsGoOn** [comment]
或者是我找的jar包不对?不是ojdbc6.jar? 应该用哪个?

**Comment by stuxuhai** [comment]
发现oracle的转义符不是`而是双引号
再重新编译下，然后reader添加个配置<keyword.escaper>&quot;</keyword.escaper>试试

**Comment by TimeIsGoOn** [comment]
大神,重新编译后又测了一遍,还是报错
```
<?xml version="1.0" encoding="UTF-8"?>

<job id="job_example">
    <reader name="jdbc">
        <url>jdbc:oracle:thin:@192.168.14.99:1521:eai</url>
        <driver>oracle.jdbc.driver.OracleDriver</driver>
        <table>V_TH_CJ_YX_SBZK_HB</table>
        <username>eai_view</username>
        <password>eai_view</password>
        <keyword.escaper>"</keyword.escaper>
        <parallelism>3</parallelism>
    </reader>

    <writer name="mongodb">
        <uri>mongodb://localhost/test.oracle</uri>
    </writer>
</job>

```


报错
```
sun@sun:~/hdata$ ls
bin  conf  lib  plugins
sun@sun:~/hdata$ ./bin/hdata -f conf/oracle.xml 
2016-07-14 17:28:40.480 [main] INFO  com.github.stuxuhai.hdata.core.HData - Reader: jdbc, Writer: mongodb
2016-07-14 17:28:40.540 [main] INFO  com.github.stuxuhai.hdata.core.HData - Executing splitter for reader.
2016-07-14 17:28:40.551 [pool-2-thread-1] INFO  com.github.stuxuhai.hdata.plugin.reader.jdbc.JDBCSplitter - Attempt to query digital primary key for table: V_TH_CJ_YX_SBZK_HB
2016-07-14 17:28:42.811 [pool-2-thread-1] INFO  com.github.stuxuhai.hdata.plugin.reader.jdbc.JDBCSplitter - Table V_TH_CJ_YX_SBZK_HB can not find digital primary key.
2016-07-14 17:28:42.998 [pool-2-thread-1] WARN  com.github.stuxuhai.hdata.plugin.reader.jdbc.JDBCSplitter - Reader parallelism is set to 3, but the "split-by" config is not given, so reader parallelism is set to default value: 1.
2016-07-14 17:28:43.010 [main] INFO  com.github.stuxuhai.hdata.core.HData - Reader parallelism: 1, Writer parallelism: 1
2016-07-14 17:28:43.067 [main] INFO  com.github.stuxuhai.hdata.core.HData - Transfer data from reader to writer...
2016-07-14 17:28:43.069 [main] INFO  com.github.stuxuhai.hdata.core.DefaultRecordCollector - The flow limit is 0 bytes/s.

2016-07-14 17:28:46.071 [main] INFO  com.github.stuxuhai.hdata.core.HData - Read: 70	Write: 70

2016-07-14 17:28:49.071 [main] INFO  com.github.stuxuhai.hdata.core.HData - Read: 210	Write: 210
2016-07-14 17:28:52.072 [main] INFO  com.github.stuxuhai.hdata.core.HData - Read: 350	Write: 350
2016-07-14 17:28:55.073 [main] INFO  com.github.stuxuhai.hdata.core.HData - Read: 490	Write: 490
2016-07-14 17:28:58.074 [main] INFO  com.github.stuxuhai.hdata.core.HData - Read: 620	Write: 620
2016-07-14 17:29:01.075 [main] INFO  com.github.stuxuhai.hdata.core.HData - Read: 750	Write: 750
2016-07-14 17:29:04.076 [main] INFO  com.github.stuxuhai.hdata.core.HData - Read: 890	Write: 890
2016-07-14 17:29:06.838 [pool-3-thread-1] ERROR com.github.stuxuhai.hdata.core.RecordEventExceptionHandler - java.lang.IllegalArgumentException: can't serialize class java.math.BigDecimal
	at org.bson.BasicBSONEncoder.putNumber(BasicBSONEncoder.java:387)
	at org.bson.BasicBSONEncoder._putObjectField(BasicBSONEncoder.java:232)
	at org.bson.BasicBSONEncoder.putObject(BasicBSONEncoder.java:185)
	at org.bson.BasicBSONEncoder.putObject(BasicBSONEncoder.java:131)
	at com.mongodb.DefaultDBEncoder.writeObject(DefaultDBEncoder.java:33)
	at com.mongodb.BSONBinaryWriter.encodeDocument(BSONBinaryWriter.java:339)
	at com.mongodb.InsertCommandMessage.writeTheWrites(InsertCommandMessage.java:45)
	at com.mongodb.InsertCommandMessage.writeTheWrites(InsertCommandMessage.java:23)
	at com.mongodb.BaseWriteCommandMessage.encodeMessageBody(BaseWriteCommandMessage.java:69)
	at com.mongodb.BaseWriteCommandMessage.encodeMessageBody(BaseWriteCommandMessage.java:23)
	at com.mongodb.RequestMessage.encode(RequestMessage.java:66)
	at com.mongodb.BaseWriteCommandMessage.encode(BaseWriteCommandMessage.java:53)
	at com.mongodb.DBCollectionImpl.sendWriteCommandMessage(DBCollectionImpl.java:473)
	at com.mongodb.DBCollectionImpl.writeWithCommandProtocol(DBCollectionImpl.java:427)
	at com.mongodb.DBCollectionImpl.insertWithCommandProtocol(DBCollectionImpl.java:387)
	at com.mongodb.DBCollectionImpl.insert(DBCollectionImpl.java:186)
	at com.mongodb.DBCollectionImpl.insert(DBCollectionImpl.java:165)
	at com.mongodb.DBCollection.insert(DBCollection.java:93)
	at com.mongodb.DBCollection.insert(DBCollection.java:78)
	at com.mongodb.DBCollection.insert(DBCollection.java:120)
	at com.github.stuxuhai.hdata.plugin.writer.mongodb.MongoDBWriter.execute(MongoDBWriter.java:56)
	at com.github.stuxuhai.hdata.core.RecordWorkHandler.onEvent(RecordWorkHandler.java:36)
	at com.github.stuxuhai.hdata.core.RecordWorkHandler.onEvent(RecordWorkHandler.java:9)
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:139)
	at java.lang.Thread.run(Thread.java:745)

2016-07-14 17:29:07.082 [main] INFO  com.github.stuxuhai.hdata.core.HData - Read: 1010	Write: 999
2016-07-14 17:29:07.082 [main] INFO  com.github.stuxuhai.hdata.core.HData - Write error.
2016-07-14 17:29:07.082 [main] INFO  com.github.stuxuhai.hdata.core.HData - Closing reader and writer.
2016-07-14 17:29:07.359 [pool-6-thread-1] ERROR com.github.stuxuhai.hdata.core.HData - java.lang.IllegalArgumentException: can't serialize class java.math.BigDecimal
	at org.bson.BasicBSONEncoder.putNumber(BasicBSONEncoder.java:387)
	at org.bson.BasicBSONEncoder._putObjectField(BasicBSONEncoder.java:232)
	at org.bson.BasicBSONEncoder.putObject(BasicBSONEncoder.java:185)
	at org.bson.BasicBSONEncoder.putObject(BasicBSONEncoder.java:131)
	at com.mongodb.DefaultDBEncoder.writeObject(DefaultDBEncoder.java:33)
	at com.mongodb.BSONBinaryWriter.encodeDocument(BSONBinaryWriter.java:339)
	at com.mongodb.InsertCommandMessage.writeTheWrites(InsertCommandMessage.java:45)
	at com.mongodb.InsertCommandMessage.writeTheWrites(InsertCommandMessage.java:23)
	at com.mongodb.BaseWriteCommandMessage.encodeMessageBody(BaseWriteCommandMessage.java:69)
	at com.mongodb.BaseWriteCommandMessage.encodeMessageBody(BaseWriteCommandMessage.java:23)
	at com.mongodb.RequestMessage.encode(RequestMessage.java:66)
	at com.mongodb.BaseWriteCommandMessage.encode(BaseWriteCommandMessage.java:53)
	at com.mongodb.DBCollectionImpl.sendWriteCommandMessage(DBCollectionImpl.java:473)
	at com.mongodb.DBCollectionImpl.writeWithCommandProtocol(DBCollectionImpl.java:427)
	at com.mongodb.DBCollectionImpl.insertWithCommandProtocol(DBCollectionImpl.java:387)
	at com.mongodb.DBCollectionImpl.insert(DBCollectionImpl.java:186)
	at com.mongodb.DBCollectionImpl.insert(DBCollectionImpl.java:165)
	at com.mongodb.DBCollection.insert(DBCollection.java:93)
	at com.mongodb.DBCollection.insert(DBCollection.java:78)
	at com.mongodb.DBCollection.insert(DBCollection.java:120)
	at com.github.stuxuhai.hdata.plugin.writer.mongodb.MongoDBWriter.close(MongoDBWriter.java:65)
	at com.github.stuxuhai.hdata.core.HData$3.call(HData.java:268)
	at com.github.stuxuhai.hdata.core.HData$3.call(HData.java:262)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

2016-07-14 17:29:07.359 [main] INFO  com.github.stuxuhai.hdata.core.HData - Job run failed!
sun@sun:~/hdata$ 
sun@sun:~/hdata$ 
sun@sun:~/hdata$ pwd
/home/sun/hdata
sun@sun:~/hdata$ 

```

**Comment by stuxuhai** [comment]
java.lang.IllegalArgumentException: can't serialize class java.math.BigDecimal

数据类型问题，不支持BigDecimal序列化

**Comment by TimeIsGoOn** [comment]
我应该怎么做呢?

**Comment by stuxuhai** [comment]
对mongodb不是很了解，这个mongodb插件的版本比较旧了，你升级下jar包版本试试
