### ISSUE TITLE
statement 预定义sql的赋值问题

### ISSUE THREAD

**Issue by balajinima** [stuxuhai/HData#9]
2016-08-09 11:39:10.996 [pool-3-thread-1] ERROR com.github.stuxuhai.hdata.core.RecordEventExceptionHandler - null
	at com.github.stuxuhai.hdata.plugin.writer.jdbc.JDBCWriter.execute(JDBCWriter.java:124)
	at com.github.stuxuhai.hdata.core.RecordWorkHandler.onEvent(RecordWorkHandler.java:36)
	at com.github.stuxuhai.hdata.core.RecordWorkHandler.onEvent(RecordWorkHandler.java:9)
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:139)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:896)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:885)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860)
	at com.mysql.jdbc.PreparedStatement.checkBounds(PreparedStatement.java:3319)
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3304)
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3341)
	at com.mysql.jdbc.PreparedStatement.setLong(PreparedStatement.java:3358)
	at com.mysql.jdbc.PreparedStatement.setObject(PreparedStatement.java:3529)
	at com.mysql.jdbc.JDBC42PreparedStatement.setObject(JDBC42PreparedStatement.java:68)
	at com.github.stuxuhai.hdata.plugin.writer.jdbc.JDBCWriter.execute(JDBCWriter.java:111)
	... 4 more

--------------------------------------------------------------------

jdbc到jdbc
-----------------------

<job id="job_example">
    <reader name="jdbc">
        <url>jdbc:mysql://127.0.0.1:8066/test_11</url>
        <driver>com.mysql.jdbc.Driver</driver>
        <table>table1</table>
        <username>root</username>
        <password>123qwe</password>
        <parallelism>100</parallelism>
 		</reader>

    <writer name="jdbc">
        <url>jdbc:mysql://127.0.0.1:3306/test_12</url>
        <driver>com.mysql.jdbc.Driver</driver>
        <table>table1</table>
        <username>root</username>
        <password>123qwe</password>
        <batch.insert.size>5000</batch.insert.size>
    </writer>
</job>

**Comment by stuxuhai** [comment]
贴下完整的配置，以及表结构

**Comment by balajinima** [comment]
xml格式的配置文件贴上去不能正常显示，我先换一个简单的表试一下再说

**Comment by ywq111** [comment]
JdbcUtils.java文件里面的getColumnTypes方法，表的分隔符Oracle上用不了：
`public static Map<String, Integer> getColumnTypes(Connection connection, String table) throws SQLException {
		StringBuilder sql = new StringBuilder();
		sql.append("SELECT * FROM ");
		sql.append("`");
		sql.append(table);
		sql.append("`");
		sql.append(" WHERE 1=2");
		sql.append(" limit 1");`

**Comment by balajinima** [comment]
@ywq111     应该不是你说的原因导致的，没有用到oracle。
生成的插入sql语句中没有变量位定义。与实际的字段数量没有对应上导致。

 String sql = String.format("INSERT INTO %s VALUES(%s)", table, Joiner.on(", ").join(placeholder));
变成 
insert into table values();  
而 statement.setObject(i + 1, record.get(i)); 
变成 statement.setObject(1, record.get(1));

所以提示
Caused by: java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).

也许和  JdbcUtils.java 的getColumnNames方法有关，也许跟多线程有关，不好复现。

**Comment by ywq111** [comment]
@balajinima  这个还是有关系的了。这种语法在oracle里面是没法执行的。还有limit 1这种也在oracle里面没法使用。

**Comment by stuxuhai** [comment]
不同的数据库SQL不一样，目前hdata这点支持的还不够完善，后面将会针对不同的数据库提供相应的支持。感谢大家的反馈
